/* GTK UI CSS */
static const gchar *style =
"window {"
    "background-image: url(\"/per/config/files/background.png\");"
    "background-position: center;"
"}"
"window * {"
    "font: 14px \"Open Sans\";"
    "color: black;"
    "box-sizing: border-box;"
"}"
"#prompt_box {"
    "background-color: white;"
    "padding: 25px 40px;"
    "margin: 0 600px 0 600px;"
    "margin-bottom: 300px;"
    "border: 2px solid #cc0066;"
    "box-shadow: 2px 2px 0 white, 2px -2px 0 white, -2px 2px 0 white, -2px -2px 0 white;"
"}"
"entry {"
    "background-color: transparent;"
    "box-shadow: none;"
    "caret-color: black;"
    "font: 14px \"monospace\";"
    "letter-spacing: 2px;"
"}"
"#message_label {"
    "color: #ff0000;"
    "font-weight: bold;"
    "text-shadow: 1px 1px 0 white, 1px -1px 0 white, -1px 1px 0 white, -1px -1px 0 white;"
"}"
;

/* GTK UI XML*/
static const gchar *ui =
"<?xml version='1.0' encoding='UTF-8'?>"
"<interface>"
  "<requires lib='gtk+' version='3.20'/>"
  "<object class='GtkWindow' id='login_window'>"
    "<property name='name'>login_window</property>"
    "<property name='can_focus'>False</property>"
    "<property name='resizable'>False</property>"
    "<property name='accept_focus'>False</property>"
    "<property name='decorated'>False</property>"
    "<child>"
      "<placeholder/>"
    "</child>"
    "<child>"
      "<object class='GtkBox' id='login_box'>"
        "<property name='name'>login_box</property>"
        "<property name='visible'>True</property>"
        "<property name='can_focus'>False</property>"
        "<property name='valign'>center</property>"
        "<property name='vexpand'>True</property>"
        "<property name='orientation'>vertical</property>"
        "<child>"
          "<object class='GtkBox' id='prompt_box'>"
            "<property name='name'>prompt_box</property>"
            "<property name='visible'>True</property>"
            "<property name='can_focus'>False</property>"
            "<property name='spacing'>25</property>"
            "<property name='homogeneous'>True</property>"
            "<child>"
              "<object class='GtkLabel' id='prompt_label'>"
                "<property name='name'>prompt_label</property>"
                "<property name='visible'>True</property>"
                "<property name='can_focus'>False</property>"
                "<property name='halign'>start</property>"
              "</object>"
              "<packing>"
                "<property name='expand'>False</property>"
                "<property name='fill'>True</property>"
                "<property name='position'>0</property>"
              "</packing>"
            "</child>"
            "<child>"
              "<object class='GtkEntry' id='prompt_entry'>"
                "<property name='name'>prompt_entry</property>"
                "<property name='visible'>True</property>"
                "<property name='can_focus'>True</property>"
                "<property name='halign'>end</property>"
                "<property name='xalign'>1</property>"
                "<property name='has_frame'>False</property>"
                "<property name='max_width_chars'>15</property>"
                "<property name='primary_icon_activatable'>False</property>"
                "<property name='secondary_icon_activatable'>False</property>"
                "<signal name='activate' handler='login_cb' swapped='no'/>"
              "</object>"
              "<packing>"
                "<property name='expand'>False</property>"
                "<property name='fill'>True</property>"
                "<property name='position'>1</property>"
              "</packing>"
            "</child>"
          "</object>"
          "<packing>"
            "<property name='expand'>False</property>"
            "<property name='fill'>True</property>"
            "<property name='position'>0</property>"
          "</packing>"
        "</child>"
        "<child>"
          "<object class='GtkLabel' id='message_label'>"
            "<property name='name'>message_label</property>"
            "<property name='visible'>True</property>"
            "<property name='can_focus'>False</property>"
            "<property name='halign'>center</property>"
            "<property name='width_chars'>25</property>"
            "<property name='max_width_chars'>50</property>"
          "</object>"
          "<packing>"
            "<property name='expand'>False</property>"
            "<property name='fill'>True</property>"
            "<property name='position'>1</property>"
          "</packing>"
        "</child>"
      "</object>"
    "</child>"
  "</object>"
"</interface>";
